version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    links:
     - db
    depends_on:
     - db
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
